Documentation mess :)
zodnrk/handout pull request #2
Opened 2020-10-07 21:52 UTC by cyrillbolliger

I've messed around regardless of anything. *Feel free to reject any suggested changes*!

2020-10-08 06:04 UTC, martyschaer requested changes

2020-10-08 06:04 UTC, martyschaer commented on handout.md
> +  <version>1</version>
`<version>` should probably be according to https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN400

2020-10-08 06:04 UTC, martyschaer commented on handout.md
> + - `groupId`  - package path of the project
An empty newline is required before lists for them to work (except directly following headings)

2020-10-08 06:04 UTC, martyschaer commented on handout.md
> -^[[git-scm.com A short history](https://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git)]
This was intended as a footnote/reference.
I would leave this out entirely otherwise.

2020-10-08 06:04 UTC, martyschaer commented on handout.md
> +* Get and install git: [https://git-scm.com/downloads](https://git-scm.com/downloads)
Prettify displayed links
```suggestion
* Get and install git: [https://git-scm.com/downloads](git-scm.com/downloads)
```

2020-10-08 06:04 UTC, martyschaer commented on handout.md
> +* `git rm --cached <pathspec>` - remove the specified file from the commit list (unstage the file), but keep the local changes
```suggestion
* `git restore --staged <pathspec>` - remove the specified file from the commit list (unstage the file), but keep the local changes
```

`rm --cached` removes the specified file from the index.

2020-10-08 06:04 UTC, martyschaer commented on handout.md
> +The fantastic merging capabilities introduced with Git enable programmers to easily unify their working copies without overwriting each others changes. This outstanding feature made git the most popu
It's usually more convenient to split long paragraphs or sentences over multiple lines (makes editing and diffing easier).
A new paragraph is only introduced with an entirely blank line.
A displayed newline within a paragraph can be achieved by adding two spaces (0x20) to the end of a line.

2020-10-08 06:04 UTC, martyschaer commented on handout.md
> +![Branching model](img/git-branching-model.png)
Image is not in the repo

2020-10-08 06:04 UTC, martyschaer commented on handout.md
> +It is very common to develop new features in a dedicated branch. This brings the advantage, that p.ex. an unfinished feature doesn't block the development of a hot-fix in the main branch.
```suggestion
It is very common to develop new features in a dedicated branch. This brings the advantage, that e.g. an unfinished feature doesn't block the development of a hot-fix in the main branch.
```

https://en.wiktionary.org/wiki/exempli_gratia

2020-10-08 18:33 UTC, cyrillbolliger commented on handout.md
> +  <version>1</version>
absolutely. My bad, I just copied the snipped from https://maven.apache.org/guides/introduction/introduction-to-the-pom.html :see_no_evil:

2020-10-08 18:37 UTC, cyrillbolliger commented on handout.md
> -^[[git-scm.com A short history](https://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git)]
ah sorry, I didn't knew the syntax for footnotes... I'll revert it.

2020-10-08 18:38 UTC, cyrillbolliger commented on handout.md
> -^[[git-scm.com A short history](https://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git)]
hmmm, this somehow confuses syntax highlighting in vim...

2020-10-08 18:41 UTC, cyrillbolliger commented on handout.md
> +The fantastic merging capabilities introduced with Git enable programmers to easily unify their working copies without overwriting each others changes. This outstanding feature made git the most popu
I was just to lazy, but took `:%!fmt -80 -s` to the rescue.

2020-10-08 18:43 UTC, cyrillbolliger commented on handout.md
> +It is very common to develop new features in a dedicated branch. This brings the advantage, that p.ex. an unfinished feature doesn't block the development of a hot-fix in the main branch.
thanks. learned something :100:

2020-10-08 18:49 UTC, merged

2020-10-08 18:50 UTC, cyrillbolliger commented
Thanks for the review :1st_place_medal:

2020-10-09 06:17 UTC, martyschaer commented on handout.md
> -^[[git-scm.com A short history](https://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git)]
That specific case works for my vim, but with large MD documents it does sometimes get confused.
Especially with cursive/bold font.