Git Data Model Section
zodnrk/handout pull request #4
Opened 2020-10-11 11:31 UTC by martyschaer

- Add section about internal data model.
- Please feel free to point out any areas that are unclear, so they can be improved.

2020-10-12 07:15 UTC, martyschaer commented
Improvement: describe how commits refer to their parents, and how branches and tags work.

2020-10-12 18:31 UTC, cyrillbolliger requested changes
- Excellent intro, thanks a lot for writing!
- As the handout should probably meet some scientific criteria, we should not use opinionated words

2020-10-12 18:31 UTC, cyrillbolliger commented on handout.md
> +^[Author and Committer can be different when merges etc. get involved].
The dot should probably be inside the brackets...?

2020-10-12 18:31 UTC, cyrillbolliger commented on handout.md
> +The file mode ^[indicating the file permissions],
"The" should be lower case: https://www.grammarly.com/blog/capitalization-after-colons/

2020-10-12 18:31 UTC, cyrillbolliger commented on handout.md
> +When you `git add` a file a _blob_ object is created and it gets added to the index.
Should we introduce the _index_ somewhere?

2020-10-12 18:32 UTC, cyrillbolliger commented on handout.md
> +- Bolliger Cyrill Alexander
```suggestion
- Bolliger Cyrill
```

2020-10-12 18:40 UTC, cyrillbolliger commented on handout.md
> +Cleverly, git only needs to update the (sub-)trees that actually change with
Maybe remove _Cleverly_ to be more scientific?

2020-10-12 18:41 UTC, cyrillbolliger commented on handout.md
> +Git's internal data model is extremely simple and elegant,
I thinks it's less opinionated if we write "Git's internal data model is _designed to be_ extremely simple and elegant"

2020-10-12 18:51 UTC, martyschaer commented
>     * Excellent intro, thanks a lot for writing!
> 
>     * As the handout should probably meet some scientific criteria, we should not use opinionated words

I think that's a great idea. I will look into resolving the issues in this either tomorrow or on Wednesday.
(We still have until the 2020-10-22 until the handout needs to be finished).

2020-10-14 19:02 UTC, cyrillbolliger approved these changes
Thanks a lot!

2020-10-20 19:43 UTC, martyschaer commented
@cyrillbolliger I've added a section about branches in the data model section.
With that, I think this branch is ready to merge.

2020-10-20 20:09 UTC, martyschaer commented
Build Job fails right now when trying to upload the PDF, possibly related to actions/upload-artifact/issues/136

2020-10-20 21:47 UTC, merged